version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.30
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3313:3306
#    volumes:
#      - db:/var/lib/mysql

volumes:
  db:
